### ISSUE TITLE
PresetTimeCallback - add_tstop! method implementation

### ISSUE THREAD

**Issue by laserschwelle** [SciML/StochasticDelayDiffEq.jl#38]
When I try to solve a SDDE with PresetTimeCallbacks the solver fails with this error message:
add_tstop!: method has not been implemented for the integrator

Julia Version v1.5.3
StochasticDelayDiffEq v0.2.8
DiffEqCallbacks v2.16.0

Example to reproduce the error:

```
using StochasticDelayDiffEq, DiffEqCallbacks

delay(u,h,p,t) = -0.1*u
stoc(u,h,p,t) = 1e-3

h(p,t) = 1.0

τ = 0.1
tspan = (0.0, 1.0)
lags = [τ];
p = []

data_stepper!(integrator) = 1.0
step_times = [0.1, 0.2]
cb = PresetTimeCallback(step_times, data_stepper!)

prob = SDDEProblem(
    delay,
    stoc,
    h,
    tspan,
    p;
    constant_lags=lags
);

sol = solve(prob, SROCK1(), dt=1e-3, callback=cb, adaptive=false)
```

If I'm not explicitly referencing `DiffEqCallbacks` the creation of the callback already fails with: UndefVarError: PresetTimeCallback not defined. Is this behavior intended?
If I'm `using DifferentialEquations` I get the same add_tstop!-error as above.

Thank you!

**Comment by ChrisRackauckas** [comment]
>If I'm not explicitly referencing DiffEqCallbacks the creation of the callback already fails with: UndefVarError: PresetTimeCallback not defined. Is this behavior intended?

Yes, it needs DiffEqCallbacks.

>When I try to solve a SDDE with PresetTimeCallbacks the solver fails with this error message

Looks like it's just a missing method.

**Comment by laserschwelle** [comment]
Changing this function
https://github.com/SciML/StochasticDelayDiffEq.jl/blob/25524178668e5b40bb74417dfc0773ca03d564ab/src/integrators/interface.jl#L217
`DiffEqBase.add_tstop!()` seems to solve the problem.

**Comment by ChrisRackauckas** [comment]
That looks like it's the right solution. It just wasn't namespaced property to overload.

**Comment by ChrisRackauckas** [comment]
To merge https://github.com/SciML/StochasticDelayDiffEq.jl/pull/50
